_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.1
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.1
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 3
gradient_accumulation_steps:
    value: 8
learning_rate:
    value: 5e-05
max_length:
    value: 512
model_name:
    value: HuggingFaceTB/SmolLM-135M
weight_decay:
    value: 0.01
